ERROR:tornado.application:Uncaught exception POST /file (58.37.133.227)
HTTPServerRequest(protocol='http', host='39.107.238.138:8886', method='POST', uri='/file', version='HTTP/1.1', remote_ip='58.37.133.227')
Traceback (most recent call last):
  File "/usr/local/python384a/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "server.py", line 42, in post
    with open(filepath,'wb') as up:
PermissionError: [Errno 13] Permission denied: '/zyroot/statics/asa/1.jpg'
ERROR:tornado.access:500 POST /file (58.37.133.227) 163.15ms
WARNING:tornado.access:404 GET /favicon.ico (58.37.133.227) 0.52ms
